<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Delete</name>
   <tag></tag>
   <elementGuidId>17cbd0ca-16a8-4353-afcc-cd7fd8f2b5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#deleteForm_69 > button.dropdown-item.delete-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Delete&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f66ae3d7-d34f-47e4-834d-0cd6ffbb0ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1a582c59-543d-4594-830a-b3ff0cb7357c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item delete-btn</value>
      <webElementGuid>1f3d8bc6-cd4a-4156-a4e8-b6fa0e91df0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>confirmDelete('deleteForm_69')</value>
      <webElementGuid>36550e13-c725-4a6a-99bb-60de407b13de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                     Delete
                                                </value>
      <webElementGuid>30f0d5db-62f3-46f6-8da9-1fe725fc32bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteForm_69&quot;)/button[@class=&quot;dropdown-item delete-btn&quot;]</value>
      <webElementGuid>5262fc76-7f90-47da-b0eb-a206d1dbc718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[6]</value>
      <webElementGuid>cd536260-5988-434a-ad62-a18d4b2c7dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='deleteForm_69']/button</value>
      <webElementGuid>d69ab947-6a6e-4726-988b-55a4ad7109ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[5]/following::button[1]</value>
      <webElementGuid>bf189295-7d5d-43e6-8096-0260f6ea5ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::button[2]</value>
      <webElementGuid>27c83930-9f17-49bf-8860-ba9e182af07d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/div/div/form/button</value>
      <webElementGuid>a78c5106-1082-4e73-b4b5-36c5f5689745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                                     Delete
                                                ' or . = '
                                                     Delete
                                                ')]</value>
      <webElementGuid>3115e827-44b8-45b0-a4f8-e03caba2da64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
