<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a status</name>
   <tag></tag>
   <elementGuidId>b02b3316-0056-44e0-acfd-d32efcbbf04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='job_status']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#job_status</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Recruitment Status&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cab5bae9-b006-418f-9149-867c0740cb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>a4178744-bdf4-4279-955a-4e57712359ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_status</value>
      <webElementGuid>06c45651-c8e9-42c6-b45d-277021faf7bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job_status</value>
      <webElementGuid>2b609f97-62ea-40e8-96cb-df2de5446d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Select a status
                                                                                    Done
                                                                                    Pending
                                                                                    Cancel
                                                                                    On-going
                                                                            </value>
      <webElementGuid>bb270f1b-fcb1-4f83-8347-d67daed2a75b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_status&quot;)</value>
      <webElementGuid>4985f3f0-f2f1-4d3f-88a3-52df14284d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='job_status']</value>
      <webElementGuid>9f692e4b-b0d1-49d9-9f84-9b0919ad63fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment Status'])[1]/following::select[1]</value>
      <webElementGuid>eac4bc2e-baee-4a28-b3b6-77b1e404e563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Positions'])[1]/following::select[1]</value>
      <webElementGuid>60964ba5-9855-41a6-8e10-8404931fb7d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created At'])[1]/preceding::select[1]</value>
      <webElementGuid>5db33e1a-8dc3-4675-b01a-441ce4442dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expires At'])[1]/preceding::select[1]</value>
      <webElementGuid>0527384a-0962-488a-a6db-afa6a40e81c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>0ceb1be2-e3d6-4cc4-8dc0-897905d6f394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'job_status' and @name = 'job_status' and (text() = '
                                        Select a status
                                                                                    Done
                                                                                    Pending
                                                                                    Cancel
                                                                                    On-going
                                                                            ' or . = '
                                        Select a status
                                                                                    Done
                                                                                    Pending
                                                                                    Cancel
                                                                                    On-going
                                                                            ')]</value>
      <webElementGuid>569db953-4114-4e48-aa89-17e7a650a796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
