<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Copy_bx bx-dots-vertical-rounded</name>
   <tag></tag>
   <elementGuidId>8a14ca73-15a2-49d1-8988-bff25069a278</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-dots-vertical-rounded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5bc30dc6-df41-4c22-8c5a-a7ba3401be2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-dots-vertical-rounded</value>
      <webElementGuid>c32d820c-e719-440a-b15a-b37a29f1d3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light-style layout-menu-fixed&quot;]/body[1]/div[@class=&quot;layout-wrapper layout-content-navbar&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;layout-page&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-xxl flex-grow-1 container-p-y&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;table-responsive text-nowrap pt-3&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[@class=&quot;table-border-bottom-0&quot;]/tr[@class=&quot;text-nowrap&quot;]/td[7]/div[@class=&quot;dropdown&quot;]/button[@class=&quot;btn p-0 dropdown-toggle hide-arrow show&quot;]/i[@class=&quot;bx bx-dots-vertical-rounded&quot;]</value>
      <webElementGuid>3d20e00d-d92d-4316-bf14-d9e46715d454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>3babf0a3-9c9e-494d-875f-5883135b2f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/div/button/i</value>
      <webElementGuid>e75dedeb-2c88-4b4d-b5b6-abe9b0d1867a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
