<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_General</name>
   <tag></tag>
   <elementGuidId>41f5ef1a-36c3-417e-a741-225332d87ec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='dynamic-form']/div/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5.card-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>0fe2d233-d50d-4594-a8ca-bbeec16e181f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-header</value>
      <webElementGuid>f6438a1e-71ec-4cce-9497-3c8ba4f63f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        General
                    </value>
      <webElementGuid>0884b2cc-69f8-480e-b2f4-6c01c8db2624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamic-form&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;card card-primary&quot;]/h5[@class=&quot;card-header&quot;]</value>
      <webElementGuid>134b1cef-6085-4347-91d6-795cf6680dc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='dynamic-form']/div/div/div/h5</value>
      <webElementGuid>888c458f-40c6-4915-ab60-d6f54ebc4a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Survey'])[1]/following::h5[1]</value>
      <webElementGuid>d0f75001-c1e3-493d-bf01-cf389b4a225f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log Out'])[1]/following::h5[1]</value>
      <webElementGuid>033a0497-c6fb-4352-99b6-6e9927be83fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cover Image'])[1]/preceding::h5[1]</value>
      <webElementGuid>d9982bbd-034b-43be-92a7-c9bb34629369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(150px x 150px)'])[1]/preceding::h5[1]</value>
      <webElementGuid>aae8dd59-32eb-4e0d-bac6-14333b48b9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='General']/parent::*</value>
      <webElementGuid>982dba0a-8c72-4096-b5b8-29362b06b9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>2f9c2d78-61c1-4e97-902f-6a378985be17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '
                        General
                    ' or . = '
                        General
                    ')]</value>
      <webElementGuid>05439677-33e7-440f-91c0-83b99af172cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
