<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Required_form-check-input border</name>
   <tag></tag>
   <elementGuidId>8854ad2c-1069-4f90-8bbd-ec307711f708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='false'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23d0b3cb-845e-4d92-b401-850b6cc48e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d4d22ccb-fe8f-4394-b882-151a69790d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input border border-2</value>
      <webElementGuid>479b7d9f-729d-41c9-89d2-612af56fa3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>steps.0.1.is_required</value>
      <webElementGuid>b64f5527-cc9f-436b-a18f-5fabebfcea71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>bcd8c419-85ae-4119-9501-d8b2cc0f126f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;surveys&quot;)/div[@class=&quot;card mt-3&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;question-section&quot;]/div[@class=&quot;question-container row&quot;]/div[@class=&quot;mb-3 col-12&quot;]/div[@class=&quot;form-group mb-3&quot;]/div[@class=&quot;form-check&quot;]/input[@class=&quot;form-check-input border border-2&quot;]</value>
      <webElementGuid>833dc974-bd98-4812-97e3-587c879270f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='false'])[2]</value>
      <webElementGuid>1ba050f2-0671-4e96-8b09-c82c88c75ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='surveys']/div/div[2]/div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>5e354ba9-18e8-4870-bf1c-b4c34296f66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>519d5ffa-fb20-434b-8607-16722b666dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>e5675c26-06a3-4fd7-8b3b-ba03246dcb63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
