<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NumberOfEntries</name>
   <tag></tag>
   <elementGuidId>ca240ff3-6a87-4514-88b5-73494dc8ecdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;limit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='limit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;limit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9bc31135-0062-4943-843b-fe122e44dc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>ff794573-cf88-47e9-a1c3-fa7c6a9957e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>89c5cabb-86ac-42b8-93b8-8404394b3d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>35fd9371-0480-4a9b-95b9-0a32b95bb12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        10
                                                        20
                                                        25
                                                        50
                                                        100
                                                    </value>
      <webElementGuid>8554e01f-5f45-4f1b-bef4-42104c400e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable_limit&quot;)/div[@class=&quot;row px-3 py-3&quot;]/div[@class=&quot;col-sm-12 col-md-6 justify-content-center justify-content-md-start py-1 py-md-0&quot;]/div[1]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>39c1ed10-a990-4126-81bd-b1df69fef96b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='limit']</value>
      <webElementGuid>b65d8224-3106-47f4-b7cf-5215984e2d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='datatable_limit']/div/div/div/select</value>
      <webElementGuid>aa22e05c-857e-4c12-af09-35c07faf5437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Entries'])[1]/following::select[1]</value>
      <webElementGuid>bb65bf84-029c-4788-84f5-1fa67c42fdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export All Temporary Employee Data'])[1]/following::select[1]</value>
      <webElementGuid>5298b638-ba4e-422b-81f9-f9f8e8e374a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/preceding::select[1]</value>
      <webElementGuid>393bd57f-57fb-4ece-9853-f97b20ac78bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by project name'])[1]/preceding::select[2]</value>
      <webElementGuid>78b979d5-4c16-4189-8590-368eb7026444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e247132a-646e-4b47-a60e-dea5271f7b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'limit' and (text() = '
                                                        10
                                                        20
                                                        25
                                                        50
                                                        100
                                                    ' or . = '
                                                        10
                                                        20
                                                        25
                                                        50
                                                        100
                                                    ')]</value>
      <webElementGuid>43b9f1ac-b732-4d63-81d4-c3f28af5f755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
