<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_toggle-password</name>
   <tag></tag>
   <elementGuidId>63816237-ed68-4e28-8fdb-e7cff98e9097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#toggle-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='toggle-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>83a8d5c3-f0ac-406a-ab77-0d4d046fafc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-eye-slash d-flex align-items-center rounded-end</value>
      <webElementGuid>5bf31209-b563-4a70-966b-69b0df0377b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-password</value>
      <webElementGuid>5bdc1407-a8b6-4655-883a-a0e15e724540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-password&quot;)</value>
      <webElementGuid>02259745-2b00-400c-8ea7-40caf4a9c561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='toggle-password']</value>
      <webElementGuid>eb828a73-9d87-4688-828f-4b6322c1d73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>fedf4b35-3480-4f83-b885-e2ac8d58b51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'toggle-password']</value>
      <webElementGuid>80b50706-c852-4a92-b7e7-c18256c38b18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
