<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization_organizations</name>
   <tag></tag>
   <elementGuidId>2bdd57b4-5e50-4b19-9a1c-620f2eb571aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='org-21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f2ac528-7eca-4d11-a9df-492bc911830b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>31c6a38f-dd63-4697-aaf7-fd281ffe94ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6b10d929-6021-41eb-8e6a-8ca672cdbbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organizations[]</value>
      <webElementGuid>7d4844ab-171d-487a-899f-dedf65944e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-21</value>
      <webElementGuid>cb850a7b-10f7-4331-9874-8419b2210b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>f50c1075-0368-41a0-b663-9793224815da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-21&quot;)</value>
      <webElementGuid>19586fd6-a870-4ec4-b205-dd4714307c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='org-21']</value>
      <webElementGuid>76174360-ed2b-4627-9b91-f5f5513e05cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>e83dbcdd-b0a3-4c49-b0fb-b01ec384b4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'organizations[]' and @id = 'org-21']</value>
      <webElementGuid>c2fbef07-0133-4beb-9767-9e99b18b8728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
