<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cng ty TNHH HIMCOM_organizations</name>
   <tag></tag>
   <elementGuidId>61ca8f1b-d3e1-4ff5-87d1-cb11326c4b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='org-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26543a79-1717-4a92-854f-74ec0127eea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>3803e30b-def5-4144-931d-b12391cbd4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b1eea8c5-9a72-4d78-84a8-ec14ad66233e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organizations[]</value>
      <webElementGuid>627f4b73-d978-4e2f-8bbc-87a426f6edb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-23</value>
      <webElementGuid>d5f536d3-68ed-4975-bb59-855272960898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>aa95a178-9d85-4bad-89b6-0d028b1ba084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-23&quot;)</value>
      <webElementGuid>7fe98cb3-7c35-4b3d-8cf0-fdd0f4c17ee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='org-23']</value>
      <webElementGuid>3e990cd6-e46c-4a04-83cf-a36d822a1605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>36f95afb-4eaf-4a37-a64c-59a60693ff77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'organizations[]' and @id = 'org-23']</value>
      <webElementGuid>efb34521-14c1-4177-b635-7fb99d141f89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
