<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Info_permissions</name>
   <tag></tag>
   <elementGuidId>de24f3b9-c62a-4ad2-8e0a-380456d247db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#per-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='per-14']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5af47849-5d0d-4852-a4e3-4b08a1201ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>b2b9073d-e8d2-4fb3-8d6e-0f0fc37ecfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>abcfcebe-4b39-4cab-9c3f-57e88ea83e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permissions[]</value>
      <webElementGuid>0e0eb1c8-a6d0-4edf-bfab-1610f8b7c845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>per-14</value>
      <webElementGuid>5b68349c-65aa-48bd-a076-7957b888bb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>28f6e1d0-95e5-4778-8f62-fef4ff757904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;per-14&quot;)</value>
      <webElementGuid>f0ecac36-b1be-46c4-815c-f923e6fce482</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='per-14']</value>
      <webElementGuid>7f685f06-0bae-4090-a3d2-c54cd2872d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permission-list']/div[11]/input</value>
      <webElementGuid>1be1b21d-1916-4db3-8928-6739bc3b35b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[11]/input</value>
      <webElementGuid>16bf79c3-21cf-46d4-b0ec-d3eba6b999e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'permissions[]' and @id = 'per-14']</value>
      <webElementGuid>1d789b77-5985-4487-81c7-8270e4b1ee30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
