<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Projects_permissions</name>
   <tag></tag>
   <elementGuidId>06aa0a71-895a-4b9b-8bdc-1e06e82f55b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#per-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='per-16']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac6d13ee-a8b9-44d5-a27f-5ab99f54149b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>4cd06031-cbbc-498d-8dc8-c3c3b6208f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1df008b6-6f67-43f2-b231-a531ceec402f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>permissions[]</value>
      <webElementGuid>efe7da91-3d47-4439-802b-51ba14ec692b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>per-16</value>
      <webElementGuid>e42c9c9a-ade1-46b9-b4b2-178f98833035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>3b2672cb-0c4d-4498-8632-5817ac83f994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;per-16&quot;)</value>
      <webElementGuid>7292abcd-6326-4453-8ce2-f9be8dec9028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='per-16']</value>
      <webElementGuid>a70e72ac-56fd-4024-a10a-ff3bb41923aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='permission-list']/div[13]/input</value>
      <webElementGuid>2bb776f5-7d48-4eeb-8a4e-954723f01512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[13]/input</value>
      <webElementGuid>2d24f6c1-7970-462e-8775-5216cad85963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'permissions[]' and @id = 'per-16']</value>
      <webElementGuid>53f4569f-cfcd-491c-80ed-1a494f0b9630</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
