<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_adminTestgmail.com</name>
   <tag></tag>
   <elementGuidId>eaf34833-6c46-4897-9ade-87b471fbb281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='org-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3b7732aa-4d41-4100-b766-22b1ae419ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-5</value>
      <webElementGuid>30107b41-1fad-4ff9-8011-de7ff0ab7b5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-name</value>
      <webElementGuid>b51982a9-196c-4b16-a0fe-4f99cf28ae27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>adminTest@gmail.com</value>
      <webElementGuid>456adfa1-aaee-4339-86b8-c53c9305f9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-name&quot;)</value>
      <webElementGuid>9102513c-cad0-431d-be05-813186f4ba2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='org-name']</value>
      <webElementGuid>9e19b067-2e2d-49c8-a62b-7eb46be53190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div/p</value>
      <webElementGuid>dde063ae-b09d-4fb2-946c-877fc9535667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::p[1]</value>
      <webElementGuid>c2bae5b8-ec93-449e-9bbb-32abd647a211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Admin account'])[1]/following::p[1]</value>
      <webElementGuid>0f8e00a4-d930-4f17-8a76-db967c56b1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::p[1]</value>
      <webElementGuid>978b308f-df1b-4af6-b96f-555951c1871c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[2]/preceding::p[2]</value>
      <webElementGuid>f1b76679-d510-40f7-abe2-f82832705a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='adminTest@gmail.com']/parent::*</value>
      <webElementGuid>a2b86a36-6e3a-4a1b-be31-9c1574dcafa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>b53dc77f-0197-49c0-b8bf-2ff336da0303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'org-name' and (text() = 'adminTest@gmail.com' or . = 'adminTest@gmail.com')]</value>
      <webElementGuid>93ee7a1f-d39e-48f0-9d21-a0d8f26595c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
