<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ngoc.tranhimcom.vn</name>
   <tag></tag>
   <elementGuidId>a3edef54-7886-420e-8ca2-68890fd0de8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='org-name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#org-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a322db3b-1ac5-4eba-a1de-8d29f12a4297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fs-5</value>
      <webElementGuid>1e77c05e-5ed5-47fa-a800-fe4719b1ae49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-name</value>
      <webElementGuid>71c4a1d7-6c82-4d11-85d6-9f368e03b0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ngoc.tran@himcom.vn</value>
      <webElementGuid>9310ef2e-77c9-4cbd-8b11-6c7dac0a0100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-name&quot;)</value>
      <webElementGuid>dc4a4334-d816-41ff-b859-61225dfcdf1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='org-name']</value>
      <webElementGuid>d7640a4b-61e6-4af2-9e54-ac80c39d5f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div/p</value>
      <webElementGuid>bf297b64-17f4-4571-b4b6-30be560ece83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::p[1]</value>
      <webElementGuid>63d14eb5-ec9d-4e96-8c43-5e60405807d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Admin account'])[1]/following::p[1]</value>
      <webElementGuid>070fe974-b971-4baa-a51b-71bb231398aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::p[1]</value>
      <webElementGuid>52961a61-d2ef-4e12-a42f-0914e50abceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[2]/preceding::p[2]</value>
      <webElementGuid>5bda7ab7-6639-465d-9810-a51324ccc2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ngoc.tran@himcom.vn']/parent::*</value>
      <webElementGuid>6d956f3b-be11-4924-8af9-fa469c93a4d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>cd208f28-5157-4009-a66e-c1b62224ea5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'org-name' and (text() = 'ngoc.tran@himcom.vn' or . = 'ngoc.tran@himcom.vn')]</value>
      <webElementGuid>2ec2334a-9e83-495c-9dfa-2d05711f9bee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
