<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_cat2name</name>
   <tag></tag>
   <elementGuidId>9733f261-f210-474d-823a-06e23033c194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cat[2][name]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cat[2][name]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dc3b8a6-04b6-4821-8ee9-0f0272149f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat[2][name]</value>
      <webElementGuid>4cbadb5e-1e2c-437a-ab04-02a37d7f5c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cat-name</value>
      <webElementGuid>12fa5528-83ca-4a2f-ba70-e531162b57b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cat-2&quot;)/td[1]/div[@class=&quot;col-10&quot;]/input[@class=&quot;form-control cat-name&quot;]</value>
      <webElementGuid>4b34ab22-8127-43e5-9704-364d9c8cc65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cat[2][name]']</value>
      <webElementGuid>cde2be91-646b-48b5-96fe-eca6f5493153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cat-2']/td/div/input</value>
      <webElementGuid>81cccd79-8385-40e4-b61f-819ffa384357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/input</value>
      <webElementGuid>c531d0e6-47fd-4d6c-8862-d7e04f251db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cat[2][name]']</value>
      <webElementGuid>d936295e-f113-4b22-b3e7-f4a48c476438</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
