<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_cat3name</name>
   <tag></tag>
   <elementGuidId>c76b73d1-699e-441b-a038-d733141ec2e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cat[3][name]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cat[3][name]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3732d876-0d21-4382-bb2c-371344374361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat[3][name]</value>
      <webElementGuid>8b4b4164-cd4a-434a-86b8-f848056c2060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cat-name</value>
      <webElementGuid>238f52ed-8039-41d7-b051-efa33ab79f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cat-3&quot;)/td[1]/div[@class=&quot;col-10&quot;]/input[@class=&quot;form-control cat-name&quot;]</value>
      <webElementGuid>390927fb-87a9-4f7b-9494-2ee9189e16f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cat[3][name]']</value>
      <webElementGuid>d5135fdd-c579-4a93-b829-a2d55f8f5a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cat-3']/td/div/input</value>
      <webElementGuid>59786199-077c-4b08-8f4a-ff07751b0f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/input</value>
      <webElementGuid>ecbd24f1-caf2-4882-acb6-336e7f0e33c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'cat[3][name]']</value>
      <webElementGuid>1b3effc2-e72e-40e4-84bb-2019c231d1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
