<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ActiveNot Active</name>
   <tag></tag>
   <elementGuidId>898b6e8d-d8fb-4edd-a4f7-1380126bebb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;cat[2][status]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='cat[2][status]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e89b7a57-5066-487d-891e-83a9cce01e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control cat-status</value>
      <webElementGuid>0a42ffdb-33fe-418d-bcdc-86f966b7dcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cat[2][status]</value>
      <webElementGuid>23598cc9-2dd4-48ac-8976-3e0a995e1ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ActiveNot Active</value>
      <webElementGuid>3dce89c3-5c6c-4827-932f-ea597d5e37ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cat-2&quot;)/td[2]/div[@class=&quot;col-8&quot;]/select[@class=&quot;form-control cat-status&quot;]</value>
      <webElementGuid>a87dd740-0438-407a-914f-46d6152596cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='cat[2][status]']</value>
      <webElementGuid>28b26385-632d-431c-8af5-a7eb9bcbf71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cat-2']/td[2]/div/select</value>
      <webElementGuid>5b904c29-10cf-42c0-9e8d-73a49a17abe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>d18398e9-6d3c-4daf-a2f7-43dc0108e332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::select[2]</value>
      <webElementGuid>7b3ab916-867d-44fb-85d0-b31afc69b17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::select[1]</value>
      <webElementGuid>1a49ee58-78b8-4b8b-9e22-e00886718840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/select</value>
      <webElementGuid>cde8a23c-b9c4-4529-89c7-25b346043e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cat[2][status]' and (text() = 'ActiveNot Active' or . = 'ActiveNot Active')]</value>
      <webElementGuid>0eb99179-299f-4ffd-8836-4a2ae393b8fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
