<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Technical Skills_ps__thumb-y</name>
   <tag></tag>
   <elementGuidId>45f1ef4c-791b-411e-90ef-7a3dc27d50e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='layout-menu']/ul/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ps__thumb-y</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56d44f72-556b-4b4b-9728-2c62393219f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps__thumb-y</value>
      <webElementGuid>99e3d42d-7304-479a-b81e-48ed857cf885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2d406c1-ab32-401b-a59d-1c075943de69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-menu&quot;)/ul[@class=&quot;menu-inner py-1 pt-3 ps ps--active-y ps--scrolling-y&quot;]/div[@class=&quot;ps__rail-y&quot;]/div[@class=&quot;ps__thumb-y&quot;]</value>
      <webElementGuid>e9a89e1d-ea41-45ae-9a67-53a298734e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='layout-menu']/ul/div[2]/div</value>
      <webElementGuid>f204fe59-2a00-4e26-b62f-6ca5e21e7bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>6bdda3e2-0334-4b41-a0e6-c0be097ed44c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
