<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Approve (1)</name>
   <tag></tag>
   <elementGuidId>d42967df-7526-433f-a6b7-8b028fa31722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#updateSelectedBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='updateSelectedBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Approve&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3f201134-90af-4ffb-88e4-cd7a2f32da81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddcc0289-8990-4dbd-9b6f-07eb8b196735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item text-primary fw-bold</value>
      <webElementGuid>0e31db1f-9e66-40ec-8273-5e8a83d9195e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updateSelectedBtn</value>
      <webElementGuid>950e60e2-9eec-4797-8190-3658878e5a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                         Approve
                    </value>
      <webElementGuid>44092e1e-2d13-41fe-8295-2861f7e0fdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updateSelectedBtn&quot;)</value>
      <webElementGuid>2c51f30d-8bd2-4348-a604-f11a9450527e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='updateSelectedBtn']</value>
      <webElementGuid>849a4f20-bfc9-4b92-a771-8cab3c371fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export data'])[1]/following::button[1]</value>
      <webElementGuid>e5c0caf0-428f-44e5-b8c1-72a463998c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More actions'])[1]/following::button[1]</value>
      <webElementGuid>143eba28-f68a-4d8a-b68e-06b42c20b233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Failed detail imported'])[1]/preceding::button[2]</value>
      <webElementGuid>8cd4db4a-2a1f-40b6-b76d-ed8710f26618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve']/parent::*</value>
      <webElementGuid>b372c352-1659-475f-93d2-daa680acf865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>35ed54ae-9ac0-47df-affa-a429636b7d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'updateSelectedBtn' and (text() = '
                         Approve
                    ' or . = '
                         Approve
                    ')]</value>
      <webElementGuid>f7111e78-36bc-4ad6-9aae-cce98d69e53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
