<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Potential_candidate-checkbox</name>
   <tag></tag>
   <elementGuidId>90cfb7f3-9e97-42e9-9419-b5628ce3ce34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.candidate-checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='10536']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;TT Sales Admin CAO THỊ TIÊN caothitien98@gmail.com 0388170555 03/05/2025 Applied Waiting Approve Potential Reject &quot;i] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>058d5c9c-e373-4a41-b02c-0d93bc8fe6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5a6fc27f-ae65-461b-b042-72340e12af0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>candidate-checkbox</value>
      <webElementGuid>74ed8187-c0d1-4420-a743-0fceee5fa3a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10536</value>
      <webElementGuid>5cc52c11-7296-4496-bd87-d734bd129a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[1]/td[@class=&quot;candidate-cell&quot;]/input[@class=&quot;candidate-checkbox&quot;]</value>
      <webElementGuid>ecf48d44-faed-4cb1-8eab-45d508212a5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='10536']</value>
      <webElementGuid>878967fd-fcf7-41af-aa3f-1cd8e0fb487e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr/td/input</value>
      <webElementGuid>93ddb9e5-ebe8-47f4-af1e-0439c28c8f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>693522e7-0874-4dde-9413-20ef23e4c963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>581fb38b-4621-4297-b9bd-9ef43e40c2de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
