<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Applied_1_2</name>
   <tag></tag>
   <elementGuidId>b6c82635-bf87-487c-a603-b4c7a2ef61b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(10) > td:nth-of-type(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr[10]/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>caa6ebb7-e27f-4f4e-88e7-69b495b7ae65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Applied
                                                                            </value>
      <webElementGuid>2afe651d-a8e3-4e82-b8c6-cb79235b8728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[10]/td[8]</value>
      <webElementGuid>46f65877-112e-46d1-a4fd-6ac1cf2739a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr[10]/td[8]</value>
      <webElementGuid>5d92b8ff-1f38-4830-9d50-8f72434962a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='thaimanhlan1201@gmail.com'])[1]/following::td[3]</value>
      <webElementGuid>a0241837-535b-456c-856b-035e7a011dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THAI MANH LAN'])[1]/following::td[4]</value>
      <webElementGuid>cd1422c1-380c-407e-829c-d1cfa7824f56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[10]/preceding::td[1]</value>
      <webElementGuid>661f17a4-59a4-4ec3-8862-e18610efddb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[10]/preceding::td[2]</value>
      <webElementGuid>65141d97-98e5-4282-adba-e22cfe78fb79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[8]</value>
      <webElementGuid>5d4f975d-743e-4eb6-9137-a2c3560d1af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Applied
                                                                            ' or . = '
                                                                                    Applied
                                                                            ')]</value>
      <webElementGuid>637802f5-0d5a-4221-bd55-86d80a891c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
