<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Potential_1</name>
   <tag></tag>
   <elementGuidId>3d5faa99-e553-4591-a2b2-c5f3d606e53f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.result-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr/td[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6c6ed1ee-d720-481d-9cbc-bab2841c4d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>result-cell</value>
      <webElementGuid>a76e9b01-73a9-4cfd-ac79-47955fa84b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Potential
                                                                            </value>
      <webElementGuid>643a9f21-a525-47f9-90ea-f61e4f604fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[1]/td[@class=&quot;result-cell&quot;]</value>
      <webElementGuid>4d37be39-77a0-4484-8216-5c9880d4e9e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr/td[9]</value>
      <webElementGuid>ac878acf-ea54-4da4-a516-f46685480cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potential'])[2]/following::td[1]</value>
      <webElementGuid>5d3f9147-1e8f-4646-8ab5-863e6f58a546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no374740@demo.estaff.vn'])[1]/following::td[4]</value>
      <webElementGuid>ef4b99d1-8173-4477-9c40-69a8da73b546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::td[1]</value>
      <webElementGuid>c666118e-5f8e-4d56-bac2-4f89410dd003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potential'])[4]/preceding::td[1]</value>
      <webElementGuid>1f5dfd11-c9e4-43d4-85e4-3ec5bdc23f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]</value>
      <webElementGuid>537cf29f-6bf1-44f2-ba3f-d13c9e1f1630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Potential
                                                                            ' or . = '
                                                                                    Potential
                                                                            ')]</value>
      <webElementGuid>ff238fd7-f5ff-4c1b-9b97-110ca944c254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
