<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Potential</name>
   <tag></tag>
   <elementGuidId>19867570-ab0f-4d33-a937-0ffe45e89842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(8)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example']/tbody/tr/td[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>306aa502-ce6a-4892-9bc1-5a30e9cb3c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                    Potential
                                                                            </value>
      <webElementGuid>afc7721b-e766-4879-80d1-69bb7cda1d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example&quot;)/tbody[1]/tr[1]/td[8]</value>
      <webElementGuid>11ecaca7-baa3-489c-9005-808b06bc1642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example']/tbody/tr/td[8]</value>
      <webElementGuid>8e620e8e-82b1-457d-a35f-88eb5604a4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no374740@demo.estaff.vn'])[1]/following::td[3]</value>
      <webElementGuid>08ba2d62-eaa8-477c-ba2e-e2242516bd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NGUYỄN HỒNG NGA'])[1]/following::td[4]</value>
      <webElementGuid>17bab0a6-0088-41fc-9f18-8fbe8b99c2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potential'])[3]/preceding::td[1]</value>
      <webElementGuid>d95757a7-c471-44f6-934e-003922f3b2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[1]/preceding::td[2]</value>
      <webElementGuid>7d5430b0-5533-4ceb-bb6c-72fcd9f5b93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]</value>
      <webElementGuid>8626c729-8073-4fa9-aeb9-08ddf31b5975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                                                                    Potential
                                                                            ' or . = '
                                                                                    Potential
                                                                            ')]</value>
      <webElementGuid>36c6e6fc-22aa-4ec5-9729-1e8c5dadd0bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
