<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Save_bx bx-check</name>
   <tag></tag>
   <elementGuidId>5e1cd20b-e0f1-4ceb-ba90-8b2040162aaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[4]/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c2e0e20c-3395-47ab-88f5-12ec3196909e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-check</value>
      <webElementGuid>fb7a3ebe-6a2d-4f67-b561-94496e045072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;light-style layout-menu-fixed&quot;]/body[1]/div[@class=&quot;layout-wrapper layout-content-navbar&quot;]/div[@class=&quot;layout-container&quot;]/div[@class=&quot;layout-page&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;container-xxl flex-grow-1 container-p-y&quot;]/div[2]/div[@class=&quot;card&quot;]/div[@class=&quot;table-responsive text-nowrap pt-3&quot;]/table[@class=&quot;table table-hover&quot;]/tbody[@class=&quot;table-border-bottom-0&quot;]/tr[@class=&quot;text-wrap&quot;]/td[4]/div[1]/button[@class=&quot;btn btn-success&quot;]/i[@class=&quot;bx bx-check&quot;]</value>
      <webElementGuid>17945949-b393-42ec-8cca-36eeeb365c88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/button/i</value>
      <webElementGuid>f4165474-b839-49c8-8357-0718eb606bc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
