<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_numberOfEntries</name>
   <tag></tag>
   <elementGuidId>e9a35837-95ff-4910-8ab5-02fa9ba08763</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;limit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='limit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;limit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d2dc7e70-7b7f-43af-aa30-df28c8c06ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>8336e6e4-3688-409c-91e6-49604304377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>fa12a726-ce43-425b-9991-f2343fc593a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>21ecce6e-7d9e-43fc-b734-49a8e6b90829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                10
                                                20
                                                25
                                                50
                                                100
                                            </value>
      <webElementGuid>20837817-3fe3-49ae-8c50-223cb834b912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable_limit&quot;)/div[@class=&quot;row px-3 py-3&quot;]/div[@class=&quot;col-sm-12 col-md-4 justify-content-center justify-content-md-start py-1 py-md-0&quot;]/div[1]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>6347a491-0479-4384-aae7-485e811a9fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='limit']</value>
      <webElementGuid>7e7e2eb3-fb55-4e41-96b4-b5c7a0764e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='datatable_limit']/div/div/div/select</value>
      <webElementGuid>1a8d7ac3-bbbc-43e0-bba0-b7d9a4c8e785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Entries'])[1]/following::select[1]</value>
      <webElementGuid>e99bbdb4-7435-42e9-b929-633e67933a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/preceding::select[1]</value>
      <webElementGuid>d2c58989-5626-45e3-8ae4-0e5ce8e3f56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter By Organization'])[1]/preceding::select[2]</value>
      <webElementGuid>3c8e1556-bf85-4f08-b531-66f46cc08ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>89c5cbb8-3a38-47c3-991e-a34baca2ae8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'limit' and (text() = '
                                                10
                                                20
                                                25
                                                50
                                                100
                                            ' or . = '
                                                10
                                                20
                                                25
                                                50
                                                100
                                            ')]</value>
      <webElementGuid>ae47b630-8eb3-4ad5-962b-d124a89a8dbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
