<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by project name_search</name>
   <tag></tag>
   <elementGuidId>f3b926df-0268-49c3-b51c-a2756d7acbfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;search&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search..&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1083c329-f7a3-4bf0-b774-d2790ade1f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>13067c79-55cb-4ea9-ad03-39200d8b0b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>2482be41-c2a0-419d-b58f-22e6124a870c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc5f43e5-006f-48b8-a8fa-f99c5dbb0f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search..</value>
      <webElementGuid>8a53439a-c516-4c2a-95a4-a21ae265d72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_1</value>
      <webElementGuid>8ca5001a-0991-441d-a357-46f3398a7621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable_limit&quot;)/div[@class=&quot;row px-3 py-3&quot;]/div[@class=&quot;col-sm-12 col-md-6 justify-content-center justify-content-md-end py-1 py-md-0&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-row&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>1bc1333b-3eea-4229-87a6-90a15627f4f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='search']</value>
      <webElementGuid>8c965845-82e7-4a9d-953c-bd4e9530dbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='datatable_limit']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>d3b5d213-2d47-45f5-a434-e9267b046543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ae1458ef-2de1-4232-ad82-9917bf4634bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @name = 'search' and @placeholder = 'Search..']</value>
      <webElementGuid>7e60e3d0-352b-4900-9c4c-2bde18c957e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
