<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Documents</name>
   <tag></tag>
   <elementGuidId>3f6aaf37-db3b-4bf8-bc9b-df1a5337ffae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mibs-documents > div.card-header > h4.card-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mibs-documents']/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>ed3e7b9c-7b71-4bcf-92cd-eaf1a2583e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title</value>
      <webElementGuid>8cb75721-a7b7-4915-8a85-4f6aff6d1d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Documents</value>
      <webElementGuid>4bac4dcf-b0e0-4239-9a99-1089f0f90443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mibs-documents&quot;)/div[@class=&quot;card-header&quot;]/h4[@class=&quot;card-title&quot;]</value>
      <webElementGuid>a368a317-9d5c-4b58-9b46-15544564a243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mibs-documents']/div/h4</value>
      <webElementGuid>1b771646-35d4-4115-9903-ce6cdaff3d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='category 2'])[1]/following::h4[1]</value>
      <webElementGuid>e0e33039-0126-4118-8cde-bf7f94507faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test add cate'])[1]/following::h4[1]</value>
      <webElementGuid>71e69c5e-d19c-4a36-895a-46a9aedcc70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preview Document 1'])[1]/preceding::h4[1]</value>
      <webElementGuid>d6554c7d-c6ea-4e23-a9f6-3003797ea5f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Document 1'])[1]/preceding::h4[1]</value>
      <webElementGuid>9492cb4d-58ff-4328-9c19-6aa89623b3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Documents']/parent::*</value>
      <webElementGuid>aae8477b-2583-443b-b117-b69d866a13ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4</value>
      <webElementGuid>06581a4e-740d-4b0f-ba10-7a171762870f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Documents' or . = 'Documents')]</value>
      <webElementGuid>b0046208-60e6-4024-bc77-de2e1225005a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
