<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Document 2_signDocuments</name>
   <tag></tag>
   <elementGuidId>4dd5ee3b-a49a-406c-aeea-6dbf0b142beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign_document_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign_document_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c038dbd-106e-4140-9a1e-7fad8f1bdae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>dcbb7a45-75e0-4624-95bc-b731eadca8b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>59a3ef63-3cc6-4bf6-b4e9-3239cec24dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign_document_2</value>
      <webElementGuid>355a5273-fa44-45c6-a232-0b99285bbe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/msword, .docx, .doc</value>
      <webElementGuid>2acd993c-d33a-4373-96dc-7901fa84840b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signDocuments[]</value>
      <webElementGuid>26586b15-921d-4b6a-ba58-51947f578b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign_document_2&quot;)</value>
      <webElementGuid>33e586bf-1b68-491f-8eb1-0fa062187227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign_document_2']</value>
      <webElementGuid>19700a1c-d72a-46ea-9748-9b148c746753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mibs-documents']/div[2]/div[4]/div/input</value>
      <webElementGuid>fe5a5d06-9e89-4c93-a992-f7d4d49d4b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>2aee0d46-c99c-4d3f-84ab-eddcde8e7f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'sign_document_2' and @name = 'signDocuments[]']</value>
      <webElementGuid>41b9524b-676d-4a9e-a7a5-68909120293c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
