<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preview Agreement_PDF</name>
   <tag></tag>
   <elementGuidId>f239d2e8-419c-4be0-abf3-f5102c8f395d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview_agreement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='preview_agreement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd186750-8b3b-4ab5-b73f-1aa0c5d9dc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>c967ad7a-8d38-49e9-8099-29eb201471e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>1351acb2-36f6-4c4d-ae34-1833da3f8bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview_agreement</value>
      <webElementGuid>7ab714d1-88f7-4fc9-854a-4aa2e26e49ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/pdf</value>
      <webElementGuid>e34150a4-afca-4e43-9eb2-40e566854d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preview_agreement</value>
      <webElementGuid>806054c7-2ea8-4799-9488-ac7028bb4d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview_agreement&quot;)</value>
      <webElementGuid>f894410f-94b5-4bdd-9bd0-8a2befdc28a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='preview_agreement']</value>
      <webElementGuid>0c35451c-f365-462f-8f76-51548ba18df3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[6]/div/input</value>
      <webElementGuid>ecb678ae-976f-496e-b7a3-f4f6cc095df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>441459b0-175f-4c2a-9fa5-88b552c6b22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'preview_agreement' and @name = 'preview_agreement']</value>
      <webElementGuid>6fda0380-af73-4a89-b584-f80f1a49981e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
