<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preview Term_PDF</name>
   <tag></tag>
   <elementGuidId>753bce85-e6ab-4b55-abf3-05a42294ba62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview_term</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='preview_term']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29d410b9-a7a8-45d3-9fd6-546aabe9ddc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>01af1db5-4e3f-4cee-a3c6-99cd856a62b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>d33b9b6e-0609-430b-a3d6-f670e2e46aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview_term</value>
      <webElementGuid>7c056734-886f-4943-a3ce-97ffd13f039d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/pdf</value>
      <webElementGuid>9afafe6f-4f1a-48e8-92f5-82206056e54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preview_term</value>
      <webElementGuid>d3a5d623-56ba-448d-ad37-8c0c56c9056d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview_term&quot;)</value>
      <webElementGuid>37795194-8055-4803-90fa-426e13161997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='preview_term']</value>
      <webElementGuid>f9fe6511-28e1-4d23-87cc-842484fb58c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[4]/div/input</value>
      <webElementGuid>abacc02d-6fea-4a1a-9113-babe08f8c265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>8255a745-ccb2-4180-bfb2-8aff746a48eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'preview_term' and @name = 'preview_term']</value>
      <webElementGuid>80f3f032-5be4-4781-b5d9-8ccda8e7aa59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
