<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Term Document_sign_term</name>
   <tag></tag>
   <elementGuidId>a7af46b0-5296-4032-b66f-5069708e20e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign_term</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign_term']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62d1b252-d381-4d9e-b082-0dd75df74b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>feab0409-aceb-4a97-b572-8f337b5cf80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>0eba2153-10c1-45c8-ac4c-75630f8ecec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign_term</value>
      <webElementGuid>e4e18071-7c95-4085-82f1-e302e75060da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/msword, .docx, .doc</value>
      <webElementGuid>9ab61f4c-32c9-4ab6-93e6-a677f9a3fac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sign_term</value>
      <webElementGuid>d52afa9b-acb8-4ffc-b582-76b7744a0f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign_term&quot;)</value>
      <webElementGuid>f7b8f60f-08e1-4328-82e1-77189ae5f0ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign_term']</value>
      <webElementGuid>5352040a-29cf-449e-b782-d01c4875db2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[5]/div/input</value>
      <webElementGuid>6a043a3c-3565-4e78-8eed-4793af248dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>087cd0c1-0160-4271-876d-4a0b783d3570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'sign_term' and @name = 'sign_term']</value>
      <webElementGuid>99fb088b-1790-4d55-b416-e0be35b2f87b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
