<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Short name (Only for company)_org-shortname</name>
   <tag></tag>
   <elementGuidId>058bc38a-15bc-404d-ac19-c72db9c0c363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-shortname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='org-shortname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6b7b44d-fcf2-478a-b5aa-9bccb1b2db7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control org-input</value>
      <webElementGuid>f96bcce1-0760-43e0-910c-21c95f979ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>org-shortname</value>
      <webElementGuid>27b8cc64-fdc1-41eb-9591-e6c765d4e7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-shortname</value>
      <webElementGuid>082466f2-36ee-44d1-9311-54bf15fe46bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Short Name</value>
      <webElementGuid>a0dbb59d-e775-4622-9694-c01cc5fc815f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-shortname&quot;)</value>
      <webElementGuid>69854563-035e-4e80-beae-92f46d272f79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='org-shortname']</value>
      <webElementGuid>7b3c2e28-ca54-40e2-a1ee-e9c93ffa9d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[2]/input</value>
      <webElementGuid>243dd57a-e23f-491f-8758-e9ce9d81334d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b9612571-7c7a-4a57-8755-a45d8fc71369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'org-shortname' and @id = 'org-shortname' and @placeholder = 'Short Name']</value>
      <webElementGuid>391d9a29-c709-4efd-a09e-fec31af53a8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
