<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preview Document 1_documents</name>
   <tag></tag>
   <elementGuidId>fdde8a6a-9c90-4487-9542-73e5d9506a99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#document_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='document_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce043c63-0ab1-43d8-afa2-c4fd47e8b1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>65ecf8fc-c393-4daf-b490-e157e725a61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>b6de0daa-a15a-4d9d-89e4-fa773a0f8b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>document_1</value>
      <webElementGuid>cb1fcb78-f3e4-4f2f-ba6a-ec6641127b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/pdf</value>
      <webElementGuid>cf0f2392-2ab9-43de-9a44-c7b90019f1f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>documents[]</value>
      <webElementGuid>9b02bc3f-b0f9-4c39-b01d-96a479cd9df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;document_1&quot;)</value>
      <webElementGuid>b0a913a5-73d0-4535-bbf7-a7b95b0950f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='document_1']</value>
      <webElementGuid>ecff94d3-74a8-4f33-aef4-ca12cc76add6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mibs-documents']/div[2]/div/div/input</value>
      <webElementGuid>556efbd0-8214-40d4-953f-1bb40c02d996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>d6b9a813-1511-4627-b811-27e6d8f7cbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'document_1' and @name = 'documents[]']</value>
      <webElementGuid>750b36d2-e884-4ce2-a21b-b7200519a137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
