<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign Document 1_signDocuments</name>
   <tag></tag>
   <elementGuidId>73644433-78a4-4c57-8e29-226c9bba74fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign_document_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign_document_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c9d99c4-6020-426d-8ca6-612136b99a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7c6a6f37-abbd-4ad7-b1c7-f01193fd76d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>faaea1f6-63c5-4c82-b474-91388beec8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign_document_1</value>
      <webElementGuid>8a0ecfd4-b660-421a-b2e6-39b55c9abafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/msword, .docx, .doc</value>
      <webElementGuid>4b3dfdcc-92d7-4082-8358-b194c583cbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signDocuments[]</value>
      <webElementGuid>367b3ec4-4e2e-48fa-8194-1f084130b0c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign_document_1&quot;)</value>
      <webElementGuid>0eeea716-3a4b-49f5-a167-01d75113b540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign_document_1']</value>
      <webElementGuid>58eb1d52-a683-4b67-ba83-262c517f5f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mibs-documents']/div[2]/div[2]/div/input</value>
      <webElementGuid>c5206b52-84c6-47a8-9ccd-21787f308dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>79dc3fb1-162f-4c3f-bcda-dd7e7db2db1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'sign_document_1' and @name = 'signDocuments[]']</value>
      <webElementGuid>cdb438ca-7468-401f-b246-e76d18dfa591</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
