<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employee Template</name>
   <tag></tag>
   <elementGuidId>42442484-260c-445b-a9a6-4b8faebe558c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employee-template</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employee-template']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a0580f2-838a-47d3-bc8e-dea1870d999b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>68825802-b98e-44f2-b2f4-fb4f02172bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>0fe15d4d-10e0-43b2-a07f-36b64ce69f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employee-template</value>
      <webElementGuid>26c928f1-49f0-48f0-8ce8-5362de7d817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/msword, .docx, .doc</value>
      <webElementGuid>2ebf9ab8-4db1-492c-8155-2e2207d7bfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>employee_template</value>
      <webElementGuid>c8342ed0-2945-4e99-819c-10a87588005f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employee-template&quot;)</value>
      <webElementGuid>a81bd3a0-694b-4a45-9b6c-19a0da772c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employee-template']</value>
      <webElementGuid>0ca818e2-590f-4697-828f-b9e3988d06f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='employee-template-wrap']/div/input</value>
      <webElementGuid>4b3e8f04-d344-4893-9303-3e9a741581b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>709c45c5-57de-4880-a73d-7bda04a8d6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'employee-template' and @name = 'employee_template']</value>
      <webElementGuid>a01c1b53-9efd-4cfa-816f-9c22f71b481b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
