<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Logo_logo</name>
   <tag></tag>
   <elementGuidId>cb5c19a5-cfbd-46c7-b3fe-59e0ddc57252</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='logo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af2a1db4-d005-4270-929b-bf4f9869cd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>03db100f-2985-4983-aa0d-f1b230255dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>95ecb414-df1f-42ce-8e6a-152860d98816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>e2013b91-ca64-4907-8c31-d7293f399cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>5767c5a7-8f35-41e6-982c-438bae783ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>69f35086-bf81-4d11-974a-0d0d1939849a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>previewImage('logo', 'logo-preview')</value>
      <webElementGuid>b67d24ea-1087-4394-bc39-a2dc0bbbe97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logo&quot;)</value>
      <webElementGuid>0626b405-749b-4c28-ae6c-f4338258b05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='logo']</value>
      <webElementGuid>629ad444-9db1-4d45-82b0-5909110b9ad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[3]/div/input</value>
      <webElementGuid>79b3e8e0-20b7-4568-81d9-47c6cbd43d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>72b059f4-bdfa-475a-8932-31289b71dbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'logo' and @name = 'logo']</value>
      <webElementGuid>74d71a90-8277-4838-8c0f-db1ab894174e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
