<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SignAgreement_Document</name>
   <tag></tag>
   <elementGuidId>92a987c7-c66c-4afc-b1bd-0439783a2c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign_agreement</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='sign_agreement']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0046d48-3663-42fb-8786-f76c8286dd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a09ccd5b-5a16-4103-b1dd-ebf1f82fd7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-input form-control</value>
      <webElementGuid>b09f2c82-9598-4127-a535-14c0513681c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign_agreement</value>
      <webElementGuid>8a2a089e-8a9d-4e00-ac3f-17fdc80a5ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/msword, .docx, .doc</value>
      <webElementGuid>7b18c86d-af21-4ba4-9bec-7ec41ba0fc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sign_agreement</value>
      <webElementGuid>617c6ea7-ee0f-4910-9207-373b0598f450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign_agreement&quot;)</value>
      <webElementGuid>3c1557ad-c9dd-4908-8826-ea0fa3c52935</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='sign_agreement']</value>
      <webElementGuid>985a87fd-6e48-41df-959a-d98638354186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[7]/div/input</value>
      <webElementGuid>693d2fb4-1145-412e-a6b5-3bce1196e661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>34a5ae45-770c-413a-aac6-4a6382300857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'sign_agreement' and @name = 'sign_agreement']</value>
      <webElementGuid>8748b0d0-cc50-4015-85c1-b55654fe6fba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
