<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Project                             _3ba129</name>
   <tag></tag>
   <elementGuidId>fce9d9cd-5f3e-4f3f-83c9-49cd6680148f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#org-type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='org-type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>91f5512c-d6dc-4a52-8c23-9a44d8214ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>org-type</value>
      <webElementGuid>609b802a-13e9-45a2-9055-11859f719480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>355196ce-25ad-4dd7-9c08-25f7dd3e0f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>org-type</value>
      <webElementGuid>a6a4a531-fc87-4743-bf4d-e84373e0039c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>toggleDocuments()</value>
      <webElementGuid>6ae141be-c6db-4f6b-9026-4c1b114e1cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                Project
                                                Company
                                                MIBS x iRED
                                            </value>
      <webElementGuid>273c79d9-4426-4da2-9f94-7a78bfe4e844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;org-type&quot;)</value>
      <webElementGuid>8e2b57c3-269c-4fbe-bd8f-c061d58800e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='org-type']</value>
      <webElementGuid>31b1489d-9e81-4e50-a32d-16f3ce619e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='org_info']/div/div[9]/table/tbody/tr/td/select</value>
      <webElementGuid>c674d268-bd23-4ee5-a231-29dda272d108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>5188e372-66e5-4164-8b5b-378d531389ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[1]</value>
      <webElementGuid>e95dc0c5-e7bf-4317-b048-6a48917b488e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categories'])[1]/preceding::select[2]</value>
      <webElementGuid>ec5265de-8fce-4196-8e28-691dc7641bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sony Cafe Activation'])[1]/preceding::select[2]</value>
      <webElementGuid>abf50d18-67f2-4239-8169-c36887c309b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4e33ebdf-5b3e-4b8d-81ff-b7a7093faf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'org-type' and @name = 'org-type' and (text() = '
                                                Project
                                                Company
                                                MIBS x iRED
                                            ' or . = '
                                                Project
                                                Company
                                                MIBS x iRED
                                            ')]</value>
      <webElementGuid>cdc82294-0e13-48b9-9e0e-faea81fd6405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
