<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NumberOfEntries</name>
   <tag></tag>
   <elementGuidId>453d468b-1681-4b8a-a2ca-fd5f6c278da2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;limit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='limit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;limit&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9dec5837-f8f5-4338-adbf-e2ac1ee83411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>d4e898a7-83f4-404b-820d-857d181bf69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>DataTables_Table_0</value>
      <webElementGuid>06ab9f42-1c5e-4f74-932d-cb4ef3f2eb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>76cd102c-0a73-4fe3-b44d-9ffaf5f6c8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        10
                                                        20
                                                        25
                                                        50
                                                        100
                                                    </value>
      <webElementGuid>b2cac33b-8d7c-4b8c-af52-7cd1885d28ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable_limit&quot;)/div[@class=&quot;row px-3 py-3 align-items-center&quot;]/div[@class=&quot;col-sm-12 col-md-6 d-flex justify-content-center justify-content-md-start py-1 py-md-0&quot;]/div[1]/select[@class=&quot;form-select&quot;]</value>
      <webElementGuid>8e324a37-01bd-4270-9e06-4523cf804cc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='limit']</value>
      <webElementGuid>fb40b317-a98b-4c2d-a903-0e17ffd041d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='datatable_limit']/div/div/div/select</value>
      <webElementGuid>1d537990-d2c7-479c-a53b-48737e038968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Entries'])[1]/following::select[1]</value>
      <webElementGuid>8dc6e1cf-2a2e-4934-8591-535044d376b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export data'])[1]/following::select[1]</value>
      <webElementGuid>555b74b6-1e1b-4c48-bf16-de2a7ce13408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/preceding::select[1]</value>
      <webElementGuid>b7f29645-e30d-4be4-94b0-f1a1c1c11d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search by employee name'])[1]/preceding::select[2]</value>
      <webElementGuid>2dd3c123-862a-449a-b6db-e6e2ed74de5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f7f254ef-9313-48ae-965a-d86f2903777b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'limit' and (text() = '
                                                        10
                                                        20
                                                        25
                                                        50
                                                        100
                                                    ' or . = '
                                                        10
                                                        20
                                                        25
                                                        50
                                                        100
                                                    ')]</value>
      <webElementGuid>dea064a2-7d6b-41f5-99fa-eca08fc9ad9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
