<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Activate</name>
   <tag></tag>
   <elementGuidId>834e25d7-230f-40b9-afda-07814cd53e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Activate&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9afbe05e-a0be-4661-b937-0412b64ab2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e8c11101-1594-4703-9381-bec997c87fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item delete-btn</value>
      <webElementGuid>47b9c007-51a7-499e-b585-85f3f3aca498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                                             Activate
                                                                                    </value>
      <webElementGuid>b48cd7c2-5386-4f45-8580-0d45533cb042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobPosition_133&quot;)/td[6]/div[@class=&quot;dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/form[@class=&quot;mg-bottom-0&quot;]/button[@class=&quot;dropdown-item delete-btn&quot;]</value>
      <webElementGuid>98c5484b-a00e-47ae-9e10-2402e6c6cf12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[7]</value>
      <webElementGuid>66b6b6e4-f4c6-40e5-b8a3-483b7a0ea727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='jobPosition_133']/td[6]/div/div/form[2]/button</value>
      <webElementGuid>fe71fe83-3a15-4b04-8f14-b3f0ef9e89a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[3]/following::button[2]</value>
      <webElementGuid>e3894085-fad1-4c62-8612-eab9aa9465df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HIM.24Admin Officer'])[1]/preceding::button[1]</value>
      <webElementGuid>722e0d64-17ff-4d27-ad01-483982a996d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On-going'])[5]/preceding::button[1]</value>
      <webElementGuid>4bb656c4-9583-4510-81ed-d258bb95b09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Activate']/parent::*</value>
      <webElementGuid>916a0a36-41ba-424e-85e3-f88cd4a90afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[6]/div/div/form[2]/button</value>
      <webElementGuid>f22dc618-1365-4ec6-9478-3c54e54f48c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
                                                                                             Activate
                                                                                    ' or . = '
                                                                                             Activate
                                                                                    ')]</value>
      <webElementGuid>d20e72e0-cf85-4b4f-8000-899d83c923ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
