<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Successfully created account</name>
   <tag></tag>
   <elementGuidId>90d39540-8e90-42cc-980a-f2b860f3e6d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#name-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07c96cc4-2387-4f2c-8b0d-ebf38a93407e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-message</value>
      <webElementGuid>c08a74a5-e2f0-4b46-b4a8-743ce97f6859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successfully created account</value>
      <webElementGuid>ec683d1e-8ef3-4a11-82e2-a75880eeb1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-message&quot;)</value>
      <webElementGuid>13ea3c57-c174-4354-b9bb-359db9bf4401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='name-message']</value>
      <webElementGuid>b388cb4d-2122-473a-9b1f-36b3906cd437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-noti']/div</value>
      <webElementGuid>7fb68680-dca3-48bc-ad3e-7b061c7906d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create admin account'])[1]/following::div[2]</value>
      <webElementGuid>35ff58a5-ee02-4ddd-8043-3c9901a85f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Admin'])[1]/following::div[2]</value>
      <webElementGuid>47d81376-d9a2-45e1-bfa5-75cf1218e0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::div[1]</value>
      <webElementGuid>19fd7514-c355-49ba-8e47-6ef2db3b4c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/preceding::div[1]</value>
      <webElementGuid>95b1773a-719d-4098-bedf-7f0e414c15cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Successfully created account']/parent::*</value>
      <webElementGuid>fea0b2b3-58d6-420a-9a3e-0fde1ddad82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>2261c70d-13c7-468e-a0de-9978600f6d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'name-message' and (text() = 'Successfully created account' or . = 'Successfully created account')]</value>
      <webElementGuid>7097e202-e99b-42ea-8a46-fa6ac1b68a48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
