<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_workshift1endDate</name>
   <tag></tag>
   <elementGuidId>fa756000-eb28-4209-bce9-5727a7b26af1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;workshift[1][endDate]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='workshift[1][endDate]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb61ef95-326f-4efd-a43f-9dac51e3fc9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>be758d25-1f2b-46c5-b22a-eafd532590a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control workshift-endDate</value>
      <webElementGuid>c3fcb398-3cea-477f-bd05-9bbcb8c9923f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workshift[1][endDate]</value>
      <webElementGuid>48d79e7e-99f8-474c-b34b-509c94880344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workshift-1&quot;)/td[@class=&quot;px-4 pb-2&quot;]/div[1]/input[@class=&quot;form-control workshift-endDate&quot;]</value>
      <webElementGuid>db79be55-7cf4-4d25-b3cc-c321d05dd3b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='workshift[1][endDate]']</value>
      <webElementGuid>6aa80071-fc2e-4ff6-9451-680031b198e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='workshift-1']/td[4]/div/input</value>
      <webElementGuid>e440504c-5493-4a52-a900-2b8429962b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/input</value>
      <webElementGuid>5dce0fea-7fa9-4b85-aeda-ab26152189fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'workshift[1][endDate]']</value>
      <webElementGuid>45ef6493-0036-4564-9432-d9c8dfc236b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
