<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End Date_workshift2startDate</name>
   <tag></tag>
   <elementGuidId>82723fb8-ab7d-4bd3-b426-50b8407dc022</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;workshift[2][startDate]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='workshift[2][startDate]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef4f45b5-36b6-41e0-88fa-9b56bac9a459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>59293e64-ede2-4269-aed7-a35c5a66da6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workshift[2][startDate]</value>
      <webElementGuid>1ad2e933-5778-48c9-9d52-3f89e318bec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control workshift-startDate</value>
      <webElementGuid>4b5e5bee-40bb-46c3-b6c7-8f4bd6212060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workshift-2&quot;)/td[@class=&quot;px-4 pb-2&quot;]/div[1]/input[@class=&quot;form-control workshift-startDate&quot;]</value>
      <webElementGuid>a972f846-f1b5-4fca-a4ac-77ca4a6b0d20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='workshift[2][startDate]']</value>
      <webElementGuid>a95e5c41-9f50-4465-9aad-7a4c4d0fe16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='workshift-2']/td[3]/div/input</value>
      <webElementGuid>42b1c705-1dac-4f53-9c37-44ae173e923f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/input</value>
      <webElementGuid>59d7c46d-3de6-47d5-b716-1e9d51fcca21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'workshift[2][startDate]']</value>
      <webElementGuid>30f66fbe-02e9-4e61-a291-3b7d82487f0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
